[0m01:23:45.420900 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D97E7990>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D8D58BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B2C190>]}


============================== 01:23:45.433914 | fc7418c8-35b5-42b3-9923-2d0e99a2af56 ==============================
[0m01:23:45.433914 [info ] [MainThread]: Running with dbt=1.9.1
[0m01:23:45.433914 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:23:45.433914 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:23:45.433914 [debug] [MainThread]: Command `dbt run` failed at 01:23:45.433914 after 0.10 seconds
[0m01:23:45.433914 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B01C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D32A4D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000221D9B2C390>]}
[0m01:23:45.433914 [debug] [MainThread]: Flushing usage events
[0m01:23:45.962992 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m11:04:37.765692 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889600D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889A0950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000029788961CD0>]}


============================== 11:04:37.770978 | df6994d5-cd0b-4938-af38-530541856bbd ==============================
[0m11:04:37.770978 [info ] [MainThread]: Running with dbt=1.9.1
[0m11:04:37.774065 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m11:04:37.775065 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:04:37.778085 [debug] [MainThread]: Command `dbt run` failed at 11:04:37.778085 after 0.14 seconds
[0m11:04:37.780075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F0610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F0910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000297889F1AD0>]}
[0m11:04:37.781105 [debug] [MainThread]: Flushing usage events
[0m11:04:38.317817 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m10:39:40.381541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8B6D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF900090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8B6410>]}


============================== 10:39:40.381541 | ecda825a-3333-4dc2-a746-24d80512b3b9 ==============================
[0m10:39:40.381541 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:39:40.381541 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m10:39:40.381541 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:39:40.381541 [debug] [MainThread]: Command `dbt run` failed at 10:39:40.381541 after 0.14 seconds
[0m10:39:40.381541 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF8BCB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215A90F2810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000215AF91C490>]}
[0m10:39:40.381541 [debug] [MainThread]: Flushing usage events
[0m10:40:46.649447 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A766A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7AF610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7AE790>]}


============================== 10:40:46.664095 | 64a64e40-7f08-4380-8eb0-e3d64d403a50 ==============================
[0m10:40:46.664095 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:40:46.664095 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m10:40:46.715198 [info ] [MainThread]: dbt version: 1.8.6
[0m10:40:46.716579 [info ] [MainThread]: python version: 3.11.5
[0m10:40:46.716579 [info ] [MainThread]: python path: C:\Users\lina_\AppData\Local\Programs\Python\Python311\python.exe
[0m10:40:46.716579 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m10:41:01.875667 [info ] [MainThread]: Using profiles dir at C:\Users\lina_\.dbt
[0m10:41:01.875667 [info ] [MainThread]: Using profiles.yml file at C:\Users\lina_\.dbt\profiles.yml
[0m10:41:01.877887 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
[0m10:41:01.879219 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m10:41:01.881029 [debug] [MainThread]: Command `dbt debug` failed at 10:41:01.881029 after 15.32 seconds
[0m10:41:01.881029 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A7D2950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A76CA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002AF5A527B10>]}
[0m10:41:01.881029 [debug] [MainThread]: Flushing usage events
[0m10:45:43.568306 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8026D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F7CF5190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F7CF5110>]}


============================== 10:45:43.569340 | 9a29aa34-ac46-48c5-89e2-930927ef6c85 ==============================
[0m10:45:43.569340 [info ] [MainThread]: Running with dbt=1.8.6
[0m10:45:43.573389 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\lina_\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt clean', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m10:45:43.573389 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\lina_\Desktop\wh_examarb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:45:43.573389 [debug] [MainThread]: Command `dbt clean` failed at 10:45:43.573389 after 0.12 seconds
[0m10:45:43.573389 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F802CD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8086850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D1F8087790>]}
[0m10:45:43.578405 [debug] [MainThread]: Flushing usage events
